import {useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const API='/api'; const strategy={name:'SPY moving-average crossover',version:1,hypothesis:'Medium-term trend persistence may exceed modeled transaction costs.',market:'US_EQUITIES',instrument:'SPY',timeframe:'1d',entry:{type:'moving_average_cross',fast_period:20,slow_period:100,direction:'above'},exit:{type:'moving_average_cross',fast_period:20,slow_period:100,direction:'below'},position:{type:'fixed_fraction',fraction:'0.05'},risk:{max_order_notional:'100.00',max_position_notional:'500.00',max_daily_loss:'25.00',max_drawdown_percent:'5.00',stop_loss_percent:'2.00'},schedule:{regular_hours_only:true,timezone:'America/New_York'}};
type Created={strategy_id:string;strategy_hash:string}; type Monitor={baseline:{checkpoint_id:string;hash:string;created_at:string;data:string};lifecycle:Record<string,string>;kill_switch:{state:string;action:string}};
function Curve({values}:{values:string[]}){const n=values.map(Number),lo=Math.min(...n),hi=Math.max(...n),range=hi-lo||1;const points=n.map((v,i)=>`${i/(n.length-1)*100},${100-(v-lo)/range*100}`).join(' ');return <svg className="curve" viewBox="0 0 100 100" role="img" aria-label="Deterministic demo backtest equity curve"><polyline points={points}/></svg>}
function App(){const [created,setCreated]=useState<Created>();const [result,setResult]=useState<Record<string,unknown>>();const [monitor,setMonitor]=useState<Monitor>();const [message,setMessage]=useState('');const [expiry,setExpiry]=useState('');const [typed,setTyped]=useState('');const [account,setAccount]=useState('demo-paper-account');
const request=async(path:string,body?:unknown)=>{const r=await fetch(API+path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw new Error(x.detail||'Request failed');return x};
const create=async()=>{try{const x=await request('/strategies',strategy);setCreated(x);setResult(undefined);setMonitor(undefined);setMessage('Candidate locked. Run deterministic demo backtest.')}catch(e){setMessage(String(e))}};
const test=async()=>{if(!created)return;try{const x=await request(`/strategies/${created.strategy_id}/backtest`,{});setResult(x.result);setMonitor(await request(`/strategies/${created.strategy_id}/monitoring`));setMessage(x.disclaimer)}catch(e){setMessage(String(e))}};
const approve=async()=>{if(!created||!expiry)return;try{const x=await request('/approvals',{strategy_id:created.strategy_id,account_id:account,mode:'paper',expires_at:expiry,typed_approval:typed});setMonitor(await request(`/strategies/${created.strategy_id}/monitoring`));setMessage(`Paper approval active until ${x.expires_at}. Broker order submission stays blocked.`)}catch(e){setMessage(String(e))}};
const required=created&&expiry?`APPROVE_AUTONOMOUS ${created.strategy_id} 1 ${account} 500.00 ${new Date(expiry).toISOString()}`:'';const curve=Array.isArray(result?.equity_curve)?result.equity_curve as string[]:[];
return <main><header><b>Guardrail Trading</b><span>DEMO · PAPER ONLY</span></header><section className="warning"><strong>Risk notice</strong><br/>Backtests, AI research, and paper trading do not predict future returns. Execution can differ materially. Loss of all allocated capital remains possible.</section><h1>Strategy control panel</h1><p className="muted">Deterministic demo data. AI never enters the order path.</p><section><h2>1. Candidate</h2><pre>{JSON.stringify(strategy,null,2)}</pre><button onClick={create}>Lock candidate</button>{created&&<p>Strategy ID: <code>{created.strategy_id}</code><br/>SHA-256: <code>{created.strategy_hash}</code></p>}</section>{created&&<section><h2>2. Backtest baseline</h2><button onClick={test}>Run demo backtest</button>{result&&<><Curve values={curve}/><dl>{Object.entries(result).filter(([k])=>!['warnings','equity_curve','kill_switch'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></div>)}</dl></>}</section>}{monitor&&<section><h2>3. Risk monitor</h2><div className={`state ${monitor.kill_switch.state.toLowerCase()}`}>{monitor.kill_switch.state} · deterministic kill switch</div><p className="muted">{monitor.kill_switch.action}</p><dl><div><dt>Baseline</dt><dd><code>{monitor.baseline.hash}</code></dd></div>{Object.entries(monitor.lifecycle).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{v}</dd></div>)}</dl></section>}{created&&result&&<section><h2>4. Paper-forward approval</h2><p>Live trading unavailable. No orders are simulated.</p><label>Paper account <input value={account} onChange={e=>setAccount(e.target.value)}/></label><label>Approval expires (UTC) <input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><p>Type exactly:</p><code className="wrap">{required}</code><label>Typed approval <input value={typed} onChange={e=>setTyped(e.target.value)}/></label><button disabled={!expiry||typed!==required} onClick={approve}>Grant paper approval</button></section>}<output>{message}</output><footer>Research requires deterministic validation, holdout testing, paper-forward observations, broker reconciliation, independent risk validation, then human approval. Execution remains hard-blocked.</footer></main>};createRoot(document.getElementById('root')!).render(<App/>);